# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # riverpod_generator menghasilkan beberapa pola yang memicu info ini.
    unnecessary_underscores: ignore
    unnecessary_import: ignore
    use_null_aware_elements: ignore

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
