name: novelku
description: "NovelKu — aplikasi baca dan tulis novel."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  # Navigation
  go_router: ^16.0.0

  # Networking
  dio: ^5.0.0

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI
  google_fonts: ^6.0.0
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.0

  # Image picking & compression
  image_picker: ^1.1.0
  flutter_image_compress: ^2.3.0

  # Native splash
  flutter_native_splash: ^2.4.0

  # Utils
  intl: ^0.20.0
  sensors_plus: ^7.1.0

flutter_native_splash:
  color: "#0F766E"
  image: assets/images/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  custom_lint: ^0.8.0
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash.png
